export const PAYROLL_HEADER_GROUPS = Object.freeze({
    IDENTITAS: 'IDENTITAS',
    PAJAK: 'PAJAK',
    ABSENSI: 'ABSENSI',
    PANEN: 'PANEN',
    PENGGAJIAN: 'PENGGAJIAN',
    TUNJANGAN: 'TUNJANGAN',
    PENDAPATAN_LAINNYA: 'PENDAPATAN LAINNYA',
    PREMI: 'PREMI',
    POTONGAN_UPAH_KOTOR: 'POTONGAN UPAH KOTOR',
    UPAH_KOTOR: 'UPAH KOTOR',
    POTONGAN_UPAH_BERSIH: 'POTONGAN UPAH BERSIH',
    UPAH_BERSIH: 'UPAH BERSIH'
});

const GROUP_ALIASES = new Map([
    ['IDENTITAS', PAYROLL_HEADER_GROUPS.IDENTITAS],
    ['PAJAK', PAYROLL_HEADER_GROUPS.PAJAK],
    ['ABSENSI', PAYROLL_HEADER_GROUPS.ABSENSI],
    ['PANEN', PAYROLL_HEADER_GROUPS.PANEN],
    ['PENGGAJIAN', PAYROLL_HEADER_GROUPS.PENGGAJIAN],
    ['TUNJANGAN', PAYROLL_HEADER_GROUPS.TUNJANGAN],
    ['PENDAPATAN LAINNYA', PAYROLL_HEADER_GROUPS.PENDAPATAN_LAINNYA],
    ['PENDAPATAN LAIN', PAYROLL_HEADER_GROUPS.PENDAPATAN_LAINNYA],
    ['INC. LAIN', PAYROLL_HEADER_GROUPS.PENDAPATAN_LAINNYA],
    ['PREMI', PAYROLL_HEADER_GROUPS.PREMI],
    ['POTONGAN UPAH KOTOR', PAYROLL_HEADER_GROUPS.POTONGAN_UPAH_KOTOR],
    ['POT KOTOR', PAYROLL_HEADER_GROUPS.POTONGAN_UPAH_KOTOR],
    ['UPAH KOTOR', PAYROLL_HEADER_GROUPS.UPAH_KOTOR],
    ['POTONGAN UPAH BERSIH', PAYROLL_HEADER_GROUPS.POTONGAN_UPAH_BERSIH],
    ['POT BERSIH', PAYROLL_HEADER_GROUPS.POTONGAN_UPAH_BERSIH],
    ['UPAH BERSIH', PAYROLL_HEADER_GROUPS.UPAH_BERSIH]
]);

const TOGGLEABLE_GROUPS = new Set([
    PAYROLL_HEADER_GROUPS.PAJAK
]);

export const normalizePayrollHeaderGroup = (label) => {
    if (typeof label !== 'string') return null;
    return GROUP_ALIASES.get(label.trim().toUpperCase()) || null;
};

export const getPayrollHeaderGroup = (label) => normalizePayrollHeaderGroup(label);

export const isPayrollGroupToggleable = (label) => {
    const group = normalizePayrollHeaderGroup(label);
    return group ? TOGGLEABLE_GROUPS.has(group) : false;
};
